import Head from "next/head";
import NextLink from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Realtime Comments</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          <li>
            <NextLink href="/posts/1">Lorem ipsum 01</NextLink>
          </li>
          <li>
            <NextLink href="/posts/2">Lorem ipsum 02</NextLink>
          </li>
        </ul>
      </main>
    </>
  );
}
